[package]
name = "min-article"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Maycon F. Melo <https://mayconfmelo.netlify.app>"]
license = "MIT-0"
description = "Simple and easy way to write ABNT-compliant articles."
categories = [ "layout", "paper" ]
keywords = [ "article", "abnt", "scientific paper" ]
exclude = [
  "dev/",
  "test/",
  "docs/",
  "scripts/",
  ".git",
  ".gitignore",
  "justfile"
]


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "/docs/assets/thumbnail.png"
